title: Hello EveryOne!
author: Niranjan Nagumalli
email: niranjannagumalli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Niranjan Nagumalli and this is my test site.
# social links
twitter_username:  NNagumalli
github_username:  niranjannagumalli
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
